In [1]:
import numpy as np

In [2]:
#1.数组创建与属性分析

# 创建3x4的二维数组
arr = np.arange(1, 13).reshape(3, 4)
print("原始数组:\n", arr)

# 任务1：打印数组属性
print("\n1. 数组属性:")
print("形状:", arr.shape)
print("维度:", arr.ndim)
print("数据类型:", arr.dtype)

# 任务2：元素乘以2
print("\n2. 元素乘以2:\n", arr * 2)

# 任务3：重塑为4x3
reshaped_arr = arr.reshape(4, 3)
print("\n3. 重塑后的数组(4x3):\n", reshaped_arr)

原始数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1. 数组属性:
形状: (3, 4)
维度: 2
数据类型: int64

2. 元素乘以2:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

3. 重塑后的数组(4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
#2.数组索引与切片

# 创建4x4数组
array = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12], 
                 [13, 14, 15, 16]])

# 任务1：提取第2行(索引为1)
print("1. 第2行:\n", array[1, :])

# 任务2：提取第3列(索引为2)
print("\n2. 第3列:\n", array[:, 2])

# 任务3：提取子数组(行1-2, 列2-3)
print("\n3. 子数组:\n", array[0:2, 1:3])

# 任务4：条件替换
array[array > 10] = 0
print("\n4. 修改后的数组:\n", array)

1. 第2行:
 [5 6 7 8]

2. 第3列:
 [ 3  7 11 15]

3. 子数组:
 [[2 3]
 [6 7]]

4. 修改后的数组:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [4]:
#3.数组运算与广播

# 创建数组A和B
A = np.arange(1, 7).reshape(3, 2)
B = np.array([10, 20])

print("数组A:\n", A)
print("数组B:\n", B)

# 任务1：逐元素相加
print("\n1. A + B:\n", A + B)

# 任务2：逐元素相乘
print("\n2. A * B:\n", A * B)

# 任务3：每行与B的点积
print("\n3. 点积结果:\n", np.dot(A, B))

数组A:
 [[1 2]
 [3 4]
 [5 6]]
数组B:
 [10 20]

1. A + B:
 [[11 22]
 [13 24]
 [15 26]]

2. A * B:
 [[ 10  40]
 [ 30  80]
 [ 50 120]]

3. 点积结果:
 [ 50 110 170]
